sudo: true
dist: xenial
language: go
go:
- 1.12
script:
- make fmtcheck
- make vet
- make test
before_deploy:
- make targets
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: T0xd6gHI2k+bi7tae2jeU2fk9hm+g4IThKxz5hkiX/jNzvCpZVMxSS83Q7NxooaZu1JeJ0+HtlXkqrkSxi78gJkAIpKlg8E+TLFF887tGlqmrGr5wnIvR5m875KYrM/hhvaGKJdq4CiHg3aGKdtb+E31cY08oGcKFhuRneuVALv15obabjXnXmRHtsT08HzWp2SFWNeX5FHIN5+1fDVQOqwpvMTMOOYWzL3BX/zAfZH+6/3+Mg5xTtKjO5ieQip6YWYJ8MMV27CX/AgfACVjbJWLsqZqypICEoea8bk1OzoM0frHMjiy0A4Vio2tb/fFQIwS+vwt2EBu/gB4YWQmub1cBI1JhGxSOobtHp2oyU8Jm/yRe+WNc2j4uubYqAuXMt4cpSqlwrSx0VWknRGh/Dsd3QPJxQVHqTCikOb/TTEo/CgekfUubwYpMgDN9kaMZbWarmJ9/490l2rJOizuqr5gjHEbC1khJTTBJK6ClToTlKhogkmOIOhSWXkAiKAW8rFMDHX3LtLQA3NG+F7WXIiFrj3uSqguVRGAkAsdUvKXWMxnmluoZeTAvbeq1MDXFqlMf4aOmAAUIKi9i0MPRtB5YVkAK0R6zjnPW8DZtAy7rvTmHPWSh4uBSBS4UZhhjM6j4LW2oc7dM5S/VQceEbyEb/dn2bziWcTPZxjHDjI=
  file: dist/*.zip
  file_glob: true
  on:
    repo: jtopjian/ansible-terraform-inventory
    tags: true
